---

oblivion:
  strength: 1
  dexterity: 1

xrxx:
  strength: 2
  stamina: 2

stalker:
  strength: 2
  stamina: 2

pillager:
  strength: 2
  stamina: 2

monk:
  strength: 2
  stamina: 2

cephalid:
  strength: 2
  stamina: 2

reptilian:
  strength: 2
  stamina: 2